spring.application.name=portfolio-service
server.port=8084

# Load root .env file natively
spring.config.import=optional:file:../../.env[.properties]
gemini.api.key=${GEMINI_API_KEY:}

# -----------------------------
# Eureka Discovery Client
# -----------------------------
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# -----------------------------
# NeonDB PostgreSQL Database
# -----------------------------
# NOTE: Use your actual NeonDB connection string! Make sure the database is named 'tradeflow'
spring.datasource.url=${PORTFOLIO_DB_URL:${AUTH_DB_URL}}
spring.datasource.username=${PORTFOLIO_DB_USERNAME:${AUTH_DB_USERNAME}}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:${AUTH_DB_PASSWORD}}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# -----------------------------
# Apache Kafka - Consumer (Listening for successful orders)
# -----------------------------
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=portfolio-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 1. See every single incoming HTTP request and where it goes
logging.level.org.springframework.web=DEBUG

# 2. See the actual SQL queries Hibernate is sending to NeonDB
logging.level.org.hibernate.SQL=DEBUG

# 3. See the values being passed into those SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 4. See exactly what is happening inside the Eureka Client
logging.level.com.netflix.discovery=DEBUG

spring.kafka.consumer.properties.spring.json.trusted.packages=*

# -----------------------------
# 5. Monitoring (Prometheus & Health)
# -----------------------------
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}