spring.application.name=portfolio-service
server.port=8084

# -----------------------------
# Eureka Discovery Client
# -----------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# -----------------------------
# NeonDB PostgreSQL Database
# -----------------------------
# NOTE: Use your actual NeonDB connection string! Make sure the database is named 'tradeflow'
spring.datasource.url=${PORTFOLIO_DB_URL:jdbc:postgresql://ep-misty-heart-a1u6ke1h-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${PORTFOLIO_DB_USERNAME:neondb_owner}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:npg_T76ZixNeJDUB}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# -----------------------------
# Apache Kafka - Consumer (Listening for successful orders)
# -----------------------------
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=portfolio-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 1. See every single incoming HTTP request and where it goes
logging.level.org.springframework.web=DEBUG

# 2. See the actual SQL queries Hibernate is sending to NeonDB
logging.level.org.hibernate.SQL=DEBUG

# 3. See the values being passed into those SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 4. See exactly what is happening inside the Eureka Client
logging.level.com.netflix.discovery=DEBUG

spring.kafka.consumer.properties.spring.json.trusted.packages=*