# Basic Settings
server.port=8080
spring.application.name=api-gateway

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Routing Logic
# Requests to /api/v1/users/** will be forwarded to the user-service
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

# Requests to /api/v1/wallets/** will be forwarded to the wallet-service
spring.cloud.gateway.server.webmvc.routes[1].id=wallet-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://wallet-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/wallets/**