server.port=9000
spring.application.name=auth-service

# Eureka Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# Load .env file natively
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5432/authdb}
spring.datasource.username=${AUTH_DB_USERNAME:postgres}
spring.datasource.password=${AUTH_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG