server.port=8082
spring.application.name=wallet-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# Load .env file natively
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=${WALLET_DB_URL:jdbc:postgresql://localhost:5432/walletdb}
spring.datasource.username=${WALLET_DB_USERNAME:postgres}
spring.datasource.password=${WALLET_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# -----------------------------
# -----------------------------
# Apache Kafka - Consumer (Listening)
# -----------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=wallet-test-debug-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Security feature: Tell Spring it is safe to convert this JSON into a Java object
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Ignore the sender's class name in headers so we can map to our own local DTOs
spring.kafka.consumer.properties.spring.json.use.type.headers=false
# Provide the default class type to deserialize the incoming JSON into
spring.kafka.consumer.properties.spring.json.value.default.type=com.tradeflow.wallet_service.dto.OrderCreatedEvent

# -----------------------------
# Apache Kafka - Producer (Replying)
# -----------------------------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
