# Basic Settings
server.port=8081
spring.application.name=user-service

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# Load .env file natively
spring.config.import=optional:file:.env[.properties]

# Neon PostgreSQL Connection
spring.datasource.url=${USER_DB_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${USER_DB_USERNAME:postgres}
spring.datasource.password=${USER_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Strategy
# 'update' will automatically create tables in Nekon based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect