spring.application.name=discovery-server
# Port where the Eureka Dashboard will be accessible
server.port=8761
# Configuration to stop the server from trying to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# -----------------------------
# Monitoring (Prometheus & Health)
# -----------------------------
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}