# -----------------------------
# 1. Basic Server Setup
# -----------------------------
server.port=8083
spring.application.name=order-service

# -----------------------------
# 2. Eureka Service Discovery
# -----------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# -----------------------------
# 3. Neon PostgreSQL Database
# -----------------------------
# IMPORTANT: Replace these with your actual NeonDB credentials!
# (You can create a new project in Neon or reuse an existing database)
spring.datasource.url=jdbc:postgresql://ep-soft-field-a1owo0ft-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yfq7dGYz2ilI
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -----------------------------
# 4. Apache Kafka Producer
# -----------------------------
spring.kafka.bootstrap-servers=localhost:9092

# We serialize the keys as standard Strings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# We serialize the values as JSON so the Wallet Service can easily read the event payload
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# -----------------------------
# 5. Apache Kafka Consumer
# -----------------------------
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Map the incoming JSON type headers (from Wallet Service) to our local Order Service DTOs
spring.kafka.consumer.properties.spring.json.type.mapping=com.tradeflow.wallet_service.dto.FundsReservedEvent:com.tradeflow.order_service.dto.FundsReservedEvent,com.tradeflow.wallet_service.dto.FundsRejectedEvent:com.tradeflow.order_service.dto.FundsRejectedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
